config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'categories#index'
  get 'profiles', to: 'profiles#show', as: :profile
  patch 'offers/:id/refuse', to: 'offers#refused', as: :refuse
  patch 'offers/:id/confirm', to: 'offers#validation', as: :validation
  patch 'offers/:id/pending', to: 'offers#pending', as: :pending
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index] do
    resources :toys, only: [:index]
  end
  resources :toys, only: [:show, :new, :create, :edit] do
    resources :offers, only: [:new, :create]
  end
  resources :toys, only: [:destroy]
  resources :offers, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :toys
  validates :name, presence: true, uniqueness: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :toy
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :offers, dependent: :destroy
  has_many_attached :photos
  validates :name, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :toys, dependent: :destroy
  has_many :offers, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name phone photo])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query"
      @categories = Category.where(sql_query, query: "%#{params[:query]}%")
    else
      @categories = Category.all
    end
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_params, only: %i[show refused destroy validation pending]

  def show
  end

  def create
    @toy = Toy.find(params[:toy_id])
    @offer = Offer.new(offer_params)
    @offer.toy = @toy
    @offer.user = current_user
    if @offer.save
      redirect_to @offer, notice: 'Offer was successfully created.'
    else
      redirect_to @toy, notice: 'Offer could not be created'
    end
  end

  def refused
    @offer.refused = true
    @offer.save
    redirect_to profile_path(current_user)
  end

  def validation
    @offer.validated = true
    @offer.save
    redirect_to profile_path(current_user)
  end

  def pending
    @offer.offer = true
    @offer.save
    redirect_to profile_path(current_user)
  end

  def destroy
    @offer.destroy
    redirect_to profile_path(current_user), alert: "Your request is cancelled"
  end

  private

  def set_params
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @toys = Toy.where(category_id: params[:category_id])
  end

  def show
    @offer = Offer.new
    @toy = Toy.find(params[:id])
  end

  def new
    @toy = Toy.new
  end

  def create
    @toy = Toy.new(toy_params)
    @toy.user = current_user
    if @toy.save
      redirect_to @toy
    else
      render :new
    end
  end

  def edit
    @toy = Toy.find(params[:id])
  end

  def update
    @toy.update(activity_params)
    redirect_to @toy
  end

  def destroy
    @toy = Toy.find(params[:id])
    @toy.destroy
    redirect_to profile_path(current_user)
  end

  private

  def toy_params
    params.require(:toy).permit(:name, :description, :price, :category_id, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="full-wrapper">
<div>
  <div class="left"></div>
  <div class="right"></div>
  <h1>Welcome to ToyStore <strong><%= current_user.first_name %></strong> </h1>
  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi sequi nesciunt nostrum consequatur dolores odit corporis veniam fugit perspiciatis, laborum, iste facilis molestias mollitia dicta commodi dolorem tempora, excepturi minus?</p>


<div class="search-block">

    <%= form_tag root_path, method: :get, class: "d-flex" do %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a category"
      %>
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
    </div>
<% end %>



  </div>


</div>





  <div class="cards">
    <% @categories.each do |category| %>
      <%= link_to category_toys_path(category), :action => 'go' do %>
        <div class="card-category", style= "background-image: linear-gradient( rgb(0 0 0 / 30%), rgb(0 0 0 / 30%)), url('<%= image_path(category.photo_path) %>')">
          <h3><%= category.name %></h3>
        </div>
      <% end %>
    <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/offers/show.html.erb
<h1>Your offer have been send to <strong><%= @offer.toy.user.first_name %></strong></h1>


<p>You have offer <%= @offer.price %> $ for the <%= @offer.toy.name %></p>


 <%= link_to toy_path(@offer.toy) do %>
            <div class="card-product">
              <%= cl_image_tag @offer.toy.photos[0].key %>
              <div class="card-product-infos">
                <h2><%= @offer.toy.name %></h2>
                <p><%= @offer.toy.description %></p>
              </div>
            </div>


          <% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/show.html.erb
<h1><%= current_user.first_name %></h1>
<h3><%= current_user.email %></h3>




<%= cl_image_tag current_user.photo.key, class: "avatar-large"%>
<%= link_to 'Edit', edit_user_registration_path(current_user) %>


<h3>My Toys</h3>

 <div>
      <% current_user.toys.each do |toy| %>
        <ul>
          <%= link_to toy_path(toy) do %>
            <div class="card-product">
              <%= cl_image_tag toy.photos[0].key %>
              <div class="card-product-infos">
                <h2><%= toy.name %></h2>
                <p><%= toy.description %></p>
                <%= link_to 'Edit', edit_toy_path(toy) %>
                <%= link_to 'Delete', toy_path(toy), method: :delete ,data: { confirm: "Are you sure?" }%>
              </div>
            </div>


          <% end %>
        </ul>
      <% end %>
  </div>


  <div class="offer-list blue">
      <h3>My Offers</h3>

      <% current_user.toys.each do |toy| %>
      <% toy.offers.each do |offer|%>
          <p><%= offer.user.first_name %> send you an offer of <%= offer.price %> $ for <%= offer.toy.name %> </p>
          <div style="display:flex; justify-content:space-around; gap: 12px">
          <%= link_to 'validate', validation_path(offer), method: :patch, class: 'btn btn-info'%>
          <%= link_to 'refuse', refuse_path(offer), method: :patch,class: 'btn btn-danger' %>
          </div>
      <% end %>
      <% end %>
  </div>

  <div class="request-list green">
    <h3>My Requests</h3>
    <% current_user.offers.each do |offer| %>
      <p>your have proposed: <%= offer.price %> $ for <%= offer.toy.name %> to <%= offer.toy.user.first_name %> </p>
     <p>validate: <%= offer.validated %> refused: <%= offer.refused %> </p>
      <%= link_to 'Delete', offer_path(offer), method: :delete ,data: { confirm: "Are you sure?" },class: 'btn btn-danger'%>
    <% end %>

  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://cdn.dribbble.com/users/77289/screenshots/7395740/toysoftheworld_1_4x.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "AddToy", new_toy_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Profile", profile_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/toys/edit.html.erb
<%= simple_form_for [@category,@toy] do |f| %>
  <%= f.association :category %>
  <%= f.input :name %>
  <%= f.input :price%>
  <%= f.input :description%>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit, class: 'btn btn-primary'%>
<% end %>

app/views/toys/index.html.erb
<h1 class="name-title "><%= @category.name.capitalize %></h1>

<div>
  <div>
      <% @toys.each do |toy| %>
        <ul>
          <%= link_to toy_path(toy) do %>
            <div class="card-product">
              <%= cl_image_tag toy.photos[0].key %>
              <div class="card-product-infos">
                <h2><%= toy.name %></h2>
                <p><%= toy.description %></p>
              </div>
            </div>


          <% end %>
        </ul>
      <% end %>
  </div>
</div>

app/views/toys/new.html.erb
<%= simple_form_for [@category,@toy] do |f| %>
  <%= f.association :category %>
  <%= f.input :name %>
  <%= f.input :price%>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit %>
<% end %>

app/views/toys/show.html.erb
<h2 class="name-title text-center"><%= @toy.name.capitalize %></h2>

  <div style="display: flex;
      justify-content: center;
      align-items: center;">
        <% if @toy.description %>
          <div><p><%= @toy.description.capitalize %></p></div>
        <% end %>
  </div>

<div class="parent">
  <% @toy.photos.each_with_index do |photo, index|  %>
    <div class="div<%= index + 1 %>">
      <%= cl_image_tag photo.key, height: "100%", width: "100%" %>
    </div>
  <% end %>

  <div class="div5" style="display: flex;
      justify-content: center;
      align-items: center;">
      <h4>price: <%= @toy.price %> $</h4>
  </div>
</div>




<div class= "offer-button">

    <%= simple_form_for [@toy, @offer] do |f| %>

      <div style="display: flex; justify-content: center;flex-direction: column;">
      <label for="price">Give your price</label>
      <%= f.input :price, label: false%>

      <%= f.button :submit, "Send your offer", class: "btn btn-flat" %>
      </div>
    <% end %>
</div>